// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYVMaFTDRwfZWSIKzsr2Ad2koI45_-G_0',
    appId: '1:200152693011:android:e05c86f39e179e060342e6',
    messagingSenderId: '200152693011',
    projectId: 'example-7e6bc',
    storageBucket: 'example-7e6bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXwHYRjD09vo0zfpCMB-rLoxu8ttQzRtw',
    appId: '1:200152693011:ios:f70a55ff5aa21da70342e6',
    messagingSenderId: '200152693011',
    projectId: 'example-7e6bc',
    storageBucket: 'example-7e6bc.firebasestorage.app',
    iosBundleId: 'com.deend.flutterTest1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRUMBJJlm7Ot6ZKc_N0Ye-wB7PfUNnbKA',
    appId: '1:200152693011:web:02d73dfa2676498e0342e6',
    messagingSenderId: '200152693011',
    projectId: 'example-7e6bc',
    authDomain: 'example-7e6bc.firebaseapp.com',
    storageBucket: 'example-7e6bc.firebasestorage.app',
    measurementId: 'G-7Q313XBY5R',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXwHYRjD09vo0zfpCMB-rLoxu8ttQzRtw',
    appId: '1:200152693011:ios:f70a55ff5aa21da70342e6',
    messagingSenderId: '200152693011',
    projectId: 'example-7e6bc',
    storageBucket: 'example-7e6bc.firebasestorage.app',
    iosBundleId: 'com.deend.flutterTest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRUMBJJlm7Ot6ZKc_N0Ye-wB7PfUNnbKA',
    appId: '1:200152693011:web:acb009eb988b42130342e6',
    messagingSenderId: '200152693011',
    projectId: 'example-7e6bc',
    authDomain: 'example-7e6bc.firebaseapp.com',
    storageBucket: 'example-7e6bc.firebasestorage.app',
    measurementId: 'G-G371HSBT66',
  );

}